name: Build Angular 16 + PrimeNG 17 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configuraci贸n de Node.js
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Paso 3: Instalaci贸n de dependencias
      - name: Install dependencies
        run: npm ci # npm ci es mejor para CI/CD porque usa package-lock.json

      # Paso 4: Verificar la versi贸n de Angular CLI
      - name: Check Angular CLI version
        run: npx ng version

      # Paso 5: Construcci贸n del proyecto Angular
      - name: Build Angular project
        run: npx ng build --configuration=production

      # Paso 6: Subir la carpeta dist como artefacto
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
