name: Build Angular 16 + PrimeNG 17 Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Configurar Node.js
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Verificar versión de npm
      - name: Check npm version
        run: npm --version

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Construir el proyecto Angular
      - name: Build Angular project
        run: npx ng build --configuration=production

      # Subir la carpeta dist como artefacto
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: Angular-Build
          path: dist/
