name: Build Angular Project

on:
  workflow_dispatch: # Permite ejecutar este workflow manualmente
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Paso 3: Verificar que los archivos del proyecto están en la raíz
      - name: List files in repository root
        run: ls -la

      # Paso 4: Instalar dependencias
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Paso 5: Construir el proyecto Angular
      - name: Build Angular project
        run: npm run build --if-present

      # Paso 6: Subir la carpeta dist como artefacto
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: Angular-Build
          path: dist/
          retention-days: 90
