name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull and Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Verificar si NVM está instalado
            if [ ! -d "$HOME/.nvm" ]; then
              echo "NVM no está instalado. Instalando..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              source ~/.nvm/nvm.sh
            else
              source ~/.nvm/nvm.sh
            fi

            # Navegar al directorio de trabajo
            mkdir -p ${{ secrets.WORK_DIR }}
            cd ${{ secrets.WORK_DIR }}

            # Verificar si el repositorio está clonado
            if [ ! -d ".git" ]; then
              echo "Clonando el repositorio..."
              git clone git@github.com:Nicovied0/CrediCar.git .  # Clonando el repositorio
            else
              echo "El repositorio ya está clonado, actualizando..."
            fi

            # Asegurarse de estar en la rama correcta (main)
            git checkout main  # Cambiar a la rama main
            git pull origin main  # Obtener los últimos cambios de la rama main

            # Verificar si package.json existe antes de ejecutar npm
            if [ -f "package.json" ]; then
              echo "Instalando dependencias..."
              npm install
              echo "Construyendo la aplicación..."
              npm run build
            else
              echo "package.json no encontrado, abortando ejecución."
              exit 1
            fi

            exit
